sudo git rm erpnext/docs/assets/old_images/erpnext/email-digest.png
sudo git rm erpnext/docs/assets/old_images/erpnext/item-price-item.png
sudo git rm erpnext/docs/assets/old_images/erpnext/item-price-list.png
sudo git rm erpnext/docs/assets/old_images/erpnext/item-price-rate.png
sudo git rm erpnext/docs/assets/old_images/erpnext/opening-entry-1.png
sudo git rm erpnext/docs/assets/old_images/erpnext/portal-new-ticket.png
sudo git rm erpnext/docs/assets/old_images/erpnext/portal-ticket-1.png
sudo git rm erpnext/docs/assets/old_images/erpnext/portal-ticket-list-empty.png
sudo git rm erpnext/docs/assets/old_images/erpnext/portal-ticket-reply.png
sudo git rm erpnext/docs/assets/old_images/erpnext/projected-quantity-stock-report.png
sudo git rm erpnext/docs/assets/old_images/erpnext/purchase-taxes.png
sudo git rm erpnext/docs/assets/old_images/erpnext/sales-analytics-customer.png
sudo git rm erpnext/docs/assets/old_images/erpnext/sales-partner-listing.png
sudo git rm erpnext/docs/assets/old_images/erpnext/sales-partner-published.png
sudo git rm erpnext/docs/assets/old_images/erpnext/sales-person-item-group-report.png
sudo git rm erpnext/docs/assets/old_images/erpnext/sales-person-target-distribution.png
sudo git rm erpnext/docs/assets/old_images/erpnext/sales-person-target-item-group.png
sudo git rm erpnext/docs/assets/old_images/erpnext/sales-person-territory-manager.png
sudo git rm erpnext/docs/assets/old_images/erpnext/sales-person-territory-report.png
sudo git rm erpnext/docs/assets/old_images/erpnext/setting-up-permissions-employee-user-permissions.png
sudo git rm erpnext/docs/assets/old_images/erpnext/setting-up-permissions-level-1.png
sudo git rm erpnext/docs/assets/old_images/erpnext/shopping-cart-1.png
sudo git rm erpnext/docs/assets/old_images/erpnext/shopping-cart-2.png
sudo git rm erpnext/docs/assets/old_images/erpnext/shopping-cart-display-1.png
sudo git rm erpnext/docs/assets/old_images/erpnext/shopping-cart-display-amount.png
sudo git rm erpnext/docs/assets/old_images/erpnext/sms-settings1.png
sudo git rm erpnext/docs/assets/old_images/erpnext/stock-reco-data.png
sudo git rm erpnext/docs/assets/old_images/erpnext/stock-reco-ledger.png
sudo git rm erpnext/docs/assets/old_images/erpnext/stock-reco-upload.png
sudo git rm erpnext/docs/assets/old_images/erpnext/subcontract.png
sudo git rm erpnext/docs/assets/old_images/erpnext/target-distribution.png
sudo git rm erpnext/docs/assets/old_images/erpnext/third-party-backups.png
sudo git rm erpnext/docs/assets/old_images/erpnext/workflow-employee-la.png
sudo git rm erpnext/docs/assets/old_images/erpnext/workflow-hr-user-la.png
sudo git rm erpnext/docs/assets/old_images/erpnext/workflow-leave-approver-la.png
sudo git rm erpnext/setup/doctype/company/fixtures/india/__init__.py
sudo git rm erpnext/setup/setup_wizard/test_setup_data.py
sudo git rm erpnext/setup/setup_wizard/test_setup_wizard.py
sudo git rm erpnext/tests/sel_tests.py
sudo git rm erpnext/tests/test_client.py

